# Generated by Django 4.2.14 on 2024-08-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_review_ambience_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.TextField(default='untitled', max_length=50),
        ),
    ]
