# Generated by Django 4.2.14 on 2024-08-13 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField(unique=True)),
                ('seats', models.PositiveIntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_number', models.IntegerField(editable=False, unique=True)),
                ('date', models.DateField()),
                ('number_of_guests', models.IntegerField()),
                ('allergies', models.TextField(blank=True, null=True)),
                ('special_requirements', models.TextField(blank=True, null=True)),
                ('reservation_status', models.IntegerField(choices=[(0, 'confirmed'), (1, 'cancelled')])),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('tables', models.ManyToManyField(related_name='reservations', to='reservation.table')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.timeslot')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
