# Generated by Django 4.2.14 on 2024-08-06 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_num', models.IntegerField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('num_of_guests', models.IntegerField()),
                ('allergies', models.TextField()),
                ('special_reqs', models.TextField()),
                ('reservation_status', models.IntegerField(choices=[(0, 'confirmed'), (1, 'cancelled')])),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
