# Generated by Django 4.2.15 on 2024-08-18 19:53

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=100, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AddField(
            model_name='reservation',
            name='first_name',
            field=models.CharField(default='bob', max_length=30, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AddField(
            model_name='reservation',
            name='last_name',
            field=models.CharField(default='smith', max_length=30, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_status',
            field=models.IntegerField(choices=[(0, 'confirmed'), (1, 'cancelled'), (2, 'expired')]),
        ),
    ]
