# Generated by Django 4.2.14 on 2024-08-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_num',
            field=models.IntegerField(unique=True),
        ),
    ]
