# Generated by Django 4.2.14 on 2024-08-07 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_reservation_reservation_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='num_of_guests',
            new_name='number_of_guests',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation_num',
            new_name='reservation_number',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='special_reqs',
            new_name='special_requirements',
        ),
    ]
