# Generated by Django 4.2.14 on 2024-08-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_rename_num_of_guests_reservation_number_of_guests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_number',
            field=models.IntegerField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='special_requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
