# Generated by Django 4.2.14 on 2024-08-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_reservation_allergies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField(unique=True)),
                ('seats', models.PositiveIntegerField(default=2)),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='tables',
            field=models.ManyToManyField(related_name='reservations', to='reservation.table'),
        ),
    ]
