# Generated by Django 4.2.14 on 2024-08-12 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_timeslot_remove_reservation_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='time_slot',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='timeslot',
            old_name='end_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='weekday',
        ),
    ]
