# Generated by Django 4.2.14 on 2024-08-12 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_rename_time_slot_reservation_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.timeslot'),
        ),
    ]
